version: '3.4'

services:
  rest:
    container_name: apiserver
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/test.pfx
      - TZ=Asia/Tokyo
    ports:
      - 1234:80
      - 1235:443
    volumes:
      - ./api:/app
      - ./https:/https
    working_dir: /app
    command: dotnet RestApiServer.dll
  db:
    container_name: postgres
    image: postgres:14.2
    ports:
      - 1500:5432
    volumes:
      - ./docker/posgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=TestPassword!
      - TZ=Asia/Tokyo
  web:
    container_name: web
    image: nginx
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

